### ISSUE TITLE
请问下这个怎么解读，是真有问题吗，如果是的话怎么解决？

### ISSUE THREAD

**Issue by duran4000** [m-sec-org/d-eyes#1]
D-Eyes Detection Result :

[ Risk  1  ]
[pid]:24800 [status]:Detect the risk of Malware Mimikatz Rule 1 | [path]:C:\Program Files (x86)\Mozilla Firefox\firefox.exe [status]:safe | [args]:safe | [network]: [127.0.0.1:51319<->127.0.0.1:51320(ESTABLISHED) 127.0.0.1:51320<->127.0.0.1:51319(ESTABLISHED) 172.19.2.144:7014<->123.56.47.62:443(ESTABLISHED) 172.19.2.144:7346<->112.126.70.115:443(ESTABLISHED) 172.19.2.144:38352<->120.232.169.49:443(ESTABLISHED) 172.19.2.144:39020<->140.82.112.25:443(ESTABLISHED) 172.19.2.144:39186<->34.107.243.93:443(ESTABLISHED) 172.19.2.144:39220<->20.205.243.166:443(ESTABLISHED) 172.19.2.144:39221<->185.199.111.133:443(ESTABLISHED) 172.19.2.144:39222<->185.199.109.154:443(ESTABLISHED) 172.19.2.144:39223<->20.205.243.168:443(ESTABLISHED) 172.19.2.144:39227<->140.82.112.22:443(ESTABLISHED)]

**Comment by zitn** [comment]
安全，都是正常连接
