### ISSUE TITLE
False positives on process scan

### ISSUE THREAD

**Issue by zengjie1** [m-sec-org/d-eyes#3]
D-Eyes Detection Result :

[ Risk  1  ]
[pid]:29048 [status]:Detect the risk of Malware Mimikatz Rule 1 | [path]:C:\Program Files\Google\Chrome\Application\chrome.exe [status]:safe | [args]:safe | [network]: null
[ Risk  2  ]
[pid]:15604 [status]:Detect the risk of Malware Mimikatz Rule 1 | [path]:C:\Program Files\Google\Chrome\Application\chrome.exe [status]:safe | [args]:safe | [network]: null

**Comment by zitn** [comment]
We recommend that you upload this chrome.exe file to [virustotal](https://www.virustotal.com/gui/) for further testing.

**Comment by zengjie1** [comment]
Signed file, valid signature

https://www.virustotal.com/gui/file/33f662aec0e59c12809d5f4cf04e6626ac08728cdc2835ead0650910bdf0f772/details

**Comment by zitn** [comment]
This is a false positive, thanks for your report.

**Comment by zengjie1** [comment]
Thank you team.

**Comment by N0body007** [comment]
> D-Eyes Detection Result :
> 
> [ Risk 1 ] [pid]:29048 [status]:Detect the risk of Malware Mimikatz Rule 1 | [path]:C:\Program Files\Google\Chrome\Application\chrome.exe [status]:safe | [args]:safe | [network]: null [ Risk 2 ] [pid]:15604 [status]:Detect the risk of Malware Mimikatz Rule 1 | [path]:C:\Program Files\Google\Chrome\Application\chrome.exe [status]:safe | [args]:safe | [network]: null

The status described after [pid] represents the security status of the process in memory. The status described after [path] represents the security status of the executable file on the disk corresponding to the process. The results above show that there is an issue with the process in memory, which is unrelated to the Chrome binary program (according to the results above, it is displayed as safe). In the future, you can judge the detection results based on this logic.
