### ISSUE TITLE
Windows环境下编译报错

### ISSUE THREAD

**Issue by mir1ce** [m-sec-org/d-eyes#4]
Windows环境下编译，这个该如何解决
# d-eyes/yaraobj
yaraobj\yaraobj.go:14:14: undefined: yara.Rules
yaraobj\yaraobj.go:17:33: undefined: yara.Rules
yaraobj\yaraobj.go:26:57: undefined: yara.MatchRule
yaraobj\yaraobj.go:32:19: undefined: yara.MatchRules
yaraobj\yaraobj.go:40:48: undefined: yara.Rules
yaraobj\yaraobj.go:41:19: undefined: NewCompiler
yaraobj\yaraobj.go:84:45: undefined: yara.Rules
yaraobj\yaraobj.go:94:24: undefined: yara.NewCompiler

**Comment by zitn** [comment]
这个是因为有cgo依赖，需要libyara

**Comment by mir1ce** [comment]
这个cgo依赖以及环境变量咋整的，网上查资料配置的全都跑不起来，能否教下，各种报错

**Comment by buding00** [comment]
需要在windows上先编译yara https://github.com/VirusTotal/yara/releases 再进行编译才可以，我们后续会放出来编译好的版本

**Comment by buding00** [comment]
参考doc/编译指南.md 进行编译

**Comment by buding00** [comment]
参考 doc/编译指南.md 进行编译
