### ISSUE TITLE
d-eyes de fs 会报错

### ISSUE THREAD

**Issue by 1156494497** [m-sec-org/d-eyes#5]
好像d-eyes de fs 会报错，无法加载检测规则

**Comment by foxhunter** [comment]
+1,报如下错误信息

Failed to load the built-in yara rule
Failed to obtain the built-in yara rule. Procedure

**Comment by 1156494497** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zitn** [comment]
请使用[v1.3.0](https://github.com/m-sec-org/d-eyes/releases/tag/v1.3.0)版本
